import sys; sys.stdout.reconfigure(encoding="utf-8")
import pandas as pd
t = pd.read_csv("C:/Users/NHN/Documents/sensortower_api/app_tags.csv")
print("columns:", t.columns.tolist())
print("rows:", len(t))
print()
print("publisher_group counts:")
print(t["publisher_group"].value_counts().to_dict())
print()
print("publisher_country top10:")
print(t["publisher_country"].value_counts().head(10).to_dict())
print()
print("publisher_group ad rates (ww):")
print(t.groupby("publisher_group")[["paid_display_pct_ww","paid_search_pct_ww"]].mean().round(1))
print()
print("publisher_group ad rates (us):")
print(t.groupby("publisher_group")[["paid_display_pct_us","paid_search_pct_us"]].mean().round(1))
